legislator_homepage:
    pattern:  /
    defaults: { _controller: LegislatorBundle:Default:index }

legislator_view:
    pattern: /document/{id}
    defaults: { _controller: LegislatorBundle:Document:view }
    methods: [GET]
    requirements:
        id: \d+

legislator_new:
    pattern: /document/new
    defaults: { _controller: LegislatorBundle:Document:new }

legislator_edit:
    pattern: /document/{id}/edit
    defaults: { _controller: LegislatorBundle:Document:edit }
    requirements:
        id: \d+

legislator_delete:
    pattern: /document/{id}/delete
    defaults: { _controller: LegislatorBundle:Document:delete }
    requirements:
        id: \d+

# comments
legislator_comment_new:
    pattern: /document/{id}/comment
    defaults: { _controller: LegislatorBundle:Comment:new }
    methods: [POST]
    requirements:
        id: \d+

legislator_comment_delete:
    pattern: /comment/{id}/delete
    defaults: { _controller: LegislatorBundle:Comment:delete }
    methods: [POST]
    requirements:
        id: \d+