legislator_homepage:
    pattern:  /
    defaults: { _controller: LegislatorBundle:Default:index }

legislator_view:
    pattern: /document/{id}
    defaults: { _controller: LegislatorBundle:Document:view }
    methods: [GET]
    requirements:
        id: \d+

legislator_view_form:
    pattern: /document/{id}
    defaults: { _controller: LegislatorBundle:Document:processForm }
    methods: [POST]
    requirements:
        id: \d+

legislator_new:
    pattern: /document/new
    defaults: { _controller: LegislatorBundle:Document:new }

legislator_edit:
    pattern: /document/{id}/edit
    defaults: { _controller: LegislatorBundle:Document:edit }
    requirements:
        id: \d+

legislator_delete:
    pattern: /document/{id}/delete
    defaults: { _controller: LegislatorBundle:Document:delete }
    requirements:
        id: \d+

legislator_process_comments:
    pattern: /document/{id}/process-comments
    defaults: { _controller: LegislatorBundle:Document:processcomments}
    requirements:
        id: \d+
        
legislator_finish_commenting:
    pattern: /document/{id}/finish-commenting
    defaults: { _controller: LegislatorBundle:Document:finishcommenting}
    requirements:
        id: \d+

legislator_document_new_version:
    pattern: /document/{id}/new-version
    defaults: { _controller: LegislatorBundle:Document:newVersion}
    requirements:
        id: \d+

# comments
legislator_comment_new:
    pattern: /document/{document_id}/comment
    defaults: { _controller: LegislatorBundle:Comment:new }
    methods: [POST]
    requirements:
        document_id: \d+
        
legislator_comment_edit:
    pattern: /document/{document_id}/comment/{id}
    defaults: { _controller: LegislatorBundle:Comment:edit }
    methods: [POST]
    requirements:
        document_id: \d+
        id: \d+

legislator_comment_delete:
    pattern: /document/{document_id}/comment/{id}/delete
    defaults: { _controller: LegislatorBundle:Comment:delete }
    methods: [POST]
    requirements:
        document_id: \d+
        id: \d+
        
legislator_comment_reply:
    pattern: /document/{document_id}/comment/{id}/reply
    defaults: { _controller: LegislatorBundle:Comment:reply }
    requirements:
        document_id: \d+
        id: \d+

# user        
legislator_user_comments:
    pattern: /user/{user_id}/comments/
    defaults: { _controller: LegislatorBundle:Comment:viewByUser }
    requirements:
        user_id: \d+
        
legislator_user_my_comments:
    pattern: /user/comments/
    defaults: { _controller: LegislatorBundle:Comment:viewByUser }
        
        