parameters:
#    legislator.example.class: Legislator\LegislatorBundle\Example

services:
#    legislator.example:
#        class: %legislator.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
