parameters:
#    legislator.example.class: Legislator\LegislatorBundle\Example

services:
    legislator_user.provider:
        class: Legislator\LegislatorBundle\Security\LegislatorUserProvider
        arguments: [@fos_user.user_manager, '%cosign_login_enabled%']

    legislator_user.registration.form.type:
        class: Legislator\LegislatorBundle\Form\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: legislator_user_registration }
            
    legislator_user.profile.form.type:
        class: Legislator\LegislatorBundle\Form\ProfileFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: legislator_user_profile }

