parameters:
#    legislator.example.class: Legislator\LegislatorBundle\Example

services:
    legislator_user.provider:
        class: Legislator\LegislatorBundle\Security\LegislatorUserProvider
        arguments: ["@fos_user.user_manager", "@service_container", "%cosign_login_enabled%"]

    legislator_user.registration.form.type:
        class: Legislator\LegislatorBundle\Form\RegistrationFormType
        arguments: ["%fos_user.model.user.class%"]
        tags:
            - { name: form.type, alias: legislator_user_registration }
            
    legislator_user.profile.form.type:
        class: Legislator\LegislatorBundle\Form\ProfileFormType
        arguments: ["%fos_user.model.user.class%"]
        tags:
            - { name: form.type, alias: legislator_user_profile }

    legislator.ldap_retriever:
        class: Legislator\LegislatorBundle\Integration\LDAPRetriever
        arguments: ["%ldap_url%", "%ldap_base_dn%"]

    legislator.teacher_search:
        class: Legislator\LegislatorBundle\Integration\LDAPTeacherSearch
        arguments: ["@legislator.ldap_retriever", "%org_unit%"]